### ISSUE TITLE
FancyVideo API has failed to load correctly

### ISSUE THREAD

**Issue by comoaig** [Nick1st/FancyVideo-API#3]
When i start a modpack it crashes bcs of FancyVideo

![image](https://user-images.githubusercontent.com/112703312/188140785-462e5eb7-dba9-439a-adca-20c0d7716dea.png)

[crash-2022-09-02_14.09.52-fml.txt](https://github.com/Crypt1-C/Encrypted_-Modpack/files/9477748/crash-2022-09-02_14.09.52-fml.txt)
[latest.log](https://github.com/Crypt1-C/Encrypted_-Modpack/files/9477751/latest.log)

**Comment by Nick1st** [comment]
Jna can't extract a file it requires, that has nothing to do with this mod (directly). Please try to reproduce this while using the normal Minecraft Launcher or the Curseforge launcher.

**Comment by comoaig** [comment]
> Jna can't extract a file it requires, that has nothing to do with this mod (directly). Please try to reproduce this while using the normal Minecraft Launcher or the Curseforge launcher.

I've tried with Curseforge launcher but the result is the same.

**Comment by Nick1st** [comment]
Please send a new log and crash report then.

**Comment by Nick1st** [comment]
# FancyVideo-API - Notice of Discontinuance
As of today, Friday, Feburary the 12th 2024 **FancyVideo-API is officially discontinued immediately**. I'm deeply sorry for all inconveniences this causes.

## Why?
I didn't make this decision light-hearted. FV-API started as a research and tech demo project. As such, the project wasn't well planed, the tech used by it was a bunch of buggy hacks, held together by loose amounts of duct-tape. That luckily got better within the first versions, however the API did never reach a level that I was satisfied with. Because of that I started a rewrite about one years ago, but due to a series of unlucky events this project stalled. Despite simply forward porting the legacy API would've been a task of hours, I decided against it. During the rewrite I was beaten time and time again to the conclusion that several layers of the API were flawed from the grounds up. That further stalled progress, and also was the reason why I didn't simply continue forward porting. During the two years I maintained FV-API, I got a much better understanding of how things work, and how they should've be done instead. 
FV-API started as a tech demo/research project and I must admit that that's all it ever was. With the knowledge I have today, I probably wouldn't have published the project on CurseForge for others to use, the project was not ready for that (nor meant for it in the beginning). I think FV still reached the goal it was originally  created for: showing whats technically possible and getting others to build upon the idea.

## What does this mean?
FV-API will no longer receive updates (This includes critical bugfixes and security updates). If you're using FV-API as a library, you should move on (simply read on for more details).

## What should I do (Modder)
I do not want to recommend a specific project, however here are two projects that I came along over the last year:
- [WATERMeDIA: Multimedia API](https://www.curseforge.com/minecraft/mc-mods/watermedia) by SrRapero720
- [A fork](https://github.com/BehindTheScenery/FancyVideo-API) by BehindTheScenery

## What's going to happen with this discord server?
I'll put this server in read-only mode until there is something new from me.
I'm still interested in the project, and I've recently been obsessed with Gstreamer. Maybe one day there will be FV-2.0 (probably as a tech demo only though!).


I just want to thank everybody who used FV-API over the last two years. I should've probably done this step half a year earlier, but I just wanted to (personally) feel sure that this is the right decision. I simply do no longer have the time required to maintain this project due to things that changed in my personal life. Thanks again for using FV-API. I hope you all stay well.
